services:
  - type: web
    name: employee-system
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn -w 4 -b 0.0.0.0:10000 src.main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: employee-db
          property: connectionString

databases:
  - name: employee-db
    plan: free
